### ISSUE TITLE
Rust support breaks for non-crates.io dependency

### ISSUE THREAD

**Issue by Pat-Lafon** [trailofbits/it-depends#67]
Hi, this is very cool. 

I was looking to run it on one of my rust projects after reading the It-depends blog post however it seems to crash if it can't find a dependency on crates.io. For my project, some of my dependencies are libraries that are stored locally in the same repository as the project. One of these is described in my `Cargo.toml` file as:
```
[dependencies.bril2json]
version      = "0.1.0"
path         = "../bril-rs/bril2json"
```
I believe the expected behavior would be to look up the crate at the following path as an alternative location(in fact it should probably be the first location searched if provided). I've included the output I received from running `it-depends .`

```
/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
resolving .:  91%|████████████████████████████████████████████████████████▏     | 115/127 [00:00<00:00, 427.84 dependencies/s]     Created binary (application) package 
    Created binary (application) package
     Created binary (application) package
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Updating crates.io index
error: no matching package named `bril2json` found
location searched: registry `crates-io`
required by package `tmpfdsfp3rm v0.1.0 (/private/var/folders/_5/8cyj_28144g15vmx7gt8n41r0000gn/T/tmpfdsfp3rm)`
    Updating crates.io index
Traceback (most recent call last):                                                                                            
  File "/opt/homebrew/bin/it-depends", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/it_depends/cli.py", line 176, in main
    package_list = resolve(
  File "/opt/homebrew/lib/python3.9/site-packages/it_depends/dependencies.py", line 970, in resolve
    result = finished.result()
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/it_depends/dependencies.py", line 777, in _process_dep
    return _DependencyResult(dep=dep, packages=list(dep.resolver.resolve(dep)), depth=depth)
  File "/opt/homebrew/lib/python3.9/site-packages/it_depends/cargo.py", line 150, in resolve
    self.resolve_from_source(SourceRepository(path=tmpdir), cache)
  File "/opt/homebrew/lib/python3.9/site-packages/it_depends/cargo.py", line 111, in resolve_from_source
    for package in get_dependencies(repo, check_for_cargo=False):
  File "/opt/homebrew/lib/python3.9/site-packages/it_depends/cargo.py", line 46, in get_dependencies
    metadata = json.loads(subprocess.check_output(["cargo", "metadata", "--format-version", "1"], cwd=repo.path))
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cargo', 'metadata', '--format-version', '1']' returned non-zero exit status 101.
    Blocking waiting for file lock on package cache
    Updating crates.io index
    Blocking waiting for file lock on package cache
```

**Comment by xanderdunn** [comment]
I would like to extend this to include Cargo dependencies that are not in crates.io, but are git dependencies. Example:
```
[dependencies]
ic-crypto-sha = { git = "https://github.com/dfinity/ic/", rev = "2ba560825f4c256e4665935bd841cdd6e08d1ca1"}
ic-types = { git = "https://github.com/dfinity/ic/", rev = "2ba560825f4c256e4665935bd841cdd6e08d1ca1"}
```

This produces `error: no matching package named`

**Comment by evandowning** [comment]
I wasn't able to reproduce this issue.

However, I observed a separate issue with running it on a `Cargo.toml` file in a local example project:

```
[package]
name = "ic-toy"
version = "0.1.0"
edition = "2021"

[dependencies]
time = "0.1.12"
ic-crypto-sha2 = { git = "https://github.com/dfinity/ic/", rev = "035a2c7" }
ic-types = { git = "https://github.com/dfinity/ic/", rev = "035a2c7" }
```

Running `it-depends v0.1.3`:
```shell
$ it-depends ~/zzz/
resolving /home/ubuntu/zzz: 0 dependencies [00:00, ? dependencies/s]    Updating crates.io index
     Locking 5 packages to latest compatible versions
      Adding time v0.1.45 (available: v0.3.45)
      Adding wasi v0.10.0+wasi-snapshot-preview1 (available: v0.10.2+wasi-snapshot-preview1)
      Adding winapi v0.3.9
      Adding winapi-i686-pc-windows-gnu v0.4.0
      Adding winapi-x86_64-pc-windows-gnu v0.4.0
  Downloaded time v0.1.45
  Downloaded wasi v0.10.0+wasi-snapshot-preview1
  Downloaded winapi v0.3.9
  Downloaded winapi-i686-pc-windows-gnu v0.4.0
  Downloaded winapi-x86_64-pc-windows-gnu v0.4.0
  Downloaded 5 crates (6.8MiB) in 0.66s (largest was `winapi-x86_64-pc-windows-gnu` at 2.8MiB)
Can not resolve /home/ubuntu/zzz
```

A similar issue occurs on the `master` branch of `it-depends` (`e9a4c37e41127eb652a150eb4dc91e4828db84ae`).

The root cause is that `cargo.py` adds packages to `cache` which never gets processed because they're not of type `SourcePackage`. Still diagnosing and determining a proper solution.
