### ISSUE TITLE
setuptools is a required dependency

### ISSUE THREAD

**Issue by cpswan** [trailofbits/it-depends#86]
After installing it-depends into a fresh Python 3.12 venv running it results in `ModuleNotFoundError: No module named 'pkg_resources'`:

```log
Traceback (most recent call last):
  File "/home/chris/python/venvs/it-depends/bin/it-depends", line 5, in <module>
    from it_depends.__main__ import main
  File "/home/chris/python/venvs/it-depends/lib/python3.12/site-packages/it_depends/__init__.py", line 5, in <module>
    from .it_depends import *
  File "/home/chris/python/venvs/it-depends/lib/python3.12/site-packages/it_depends/it_depends.py", line 2, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

Manually installing setuptools with `pip install setuptools` fixes that problem, but it could be fixed at source by adding setuptools to setup.py

**Comment by evandowning** [comment]
Closing, as we have moved away from setuptools.
